CREATE TABLE shopping_cart (
id SERIAL PRIMARY KEY,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
qty INTEGER NOT NULL DEFAULT 1,
note TEXT NULL,
created TIMESTAMP DEFAULT NOW()
);