CREATE TABLE order_items (
id SERIAL PRIMARY KEY,
order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
product_id INTEGER REFERENCES products(id) ON DELETE SET DEFAULT,
product_info JSON NOT NULL DEFAULT '{}',
qty INTEGER NOT NULL DEFAULT 1,
price NUMERIC(18,3) NOT NULL DEFAULT 0,
total NUMERIC(18,3) NOT NULL DEFAULT 0,
note TEXT NULL,
status INTEGER NOT NULL DEFAULT 1
);