CREATE TABLE orders (
id SERIAL PRIMARY KEY,
user_id INTEGER REFERENCES users(id) ON DELETE SET DEFAULT,
user_info JSON NOT NULL DEFAULT '{}',
qty_count INTEGER NOT NULL DEFAULT 1,
total NUMERIC(18,3) NOT NULL DEFAULT 0,
status INTEGER NOT NULL DEFAULT 1,
confirmed_by INTEGER NOT NULL DEFAULT 0,
confirmed_date TIMESTAMP NULL DEFAULT NULL,
payment_type INTEGER NOT NULL DEFAULT 1,
note TEXT NULL,
created TIMESTAMP DEFAULT NOW()
);