CREATE TABLE products (
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
description TEXT NOT NULL,
category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
price NUMERIC(18,3) NOT NULL DEFAULT 0.000,
stock INTEGER NOT NULL DEFAULT 0,
details JSON NOT NULL DEFAULT '{}',
image VARCHAR(255) NULL,
status INTEGER NOT NULL DEFAULT 0,
created TIMESTAMP DEFAULT NOW()
);